spring:
  application:
    name: genAi_chatApp
  ai:
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        use-tls: false
client:
  openai:
    key: dial-gw1gaf2ivv34ziy04hokk8n9mdn
    endpoint: https://ai-proxy.lab.epam.com
    deploymentName: gpt-35-turbo-0125
server:
  port: 8082

epam:
  dial:
    deployment-names-api: https://ai-proxy.lab.epam.com/openai/deployments

vector:
  collection:
    name: my_embeddings

rag:
  documents:
    folder: src/main/resources/data

