version: '3.7'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_container
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "${QDRANT_STORAGE}:/qdrant/storage"
    restart: unless-stopped
